name: Noor Auto Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bot
        run: python bot.py
